### ISSUE TITLE
Loop within validate function

### ISSUE THREAD

**Issue by elaruwan** [wangpinggl/TREQS#4]
Hello,

I am trying to run the validate task after running the training function.  However, it appears to get stuck in a while (true), or while 1: loop.

Could you please let me know what the function is of validate here?

This is the end of the output before it appears to spin within the loop.

[>>>>>>>>>>>>>>>>>>>>>>>>>]100%
model=8_100, loss=0.1307, time=14.4047
model=9_400, loss=0.1307, time=14.0367
model=8_200, loss=0.1311, time=14.2598
model=12_0, loss=0.1324, time=14.7749
model=11_499, loss=0.1339, time=15.5923
^N^An^CTraceback (most recent call last):
  File "main.py", line 67, in <module>
    model.validate()
  File "/home/ubuntu/treqs/TREQS/LeafNATS/engines/end2end_large.py", line 252, in validate
    '..', 'nats_results', sorted(list(self.train_models))[0]+'*.model'))
  File "/home/ubuntu/anaconda3/lib/python3.7/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/home/ubuntu/anaconda3/lib/python3.7/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/home/ubuntu/anaconda3/lib/python3.7/glob.py", line 80, in _glob1
    names = list(_iterdir(dirname, dironly))
  File "/home/ubuntu/anaconda3/lib/python3.7/glob.py", line 125, in _iterdir
    yield entry.name
KeyboardInterrupt

**Comment by elaruwan** [comment]
Thanks for response.  Validation happens at training time so loops to discover new model ouptut
